default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_teq_app_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: web_teq_app_test

production:
  <<: *default
  database: web_teq_app_production
  username: web_teq_app
  password: <%= ENV['WEB_TEQ_APP_DATABASE_PASSWORD'] %>
